// <auto-generated />
namespace HesapRehberi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Allll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Allll));
        
        string IMigrationMetadata.Id
        {
            get { return "202012311013473_Allll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
